### ISSUE TITLE
Web Summit 2019

### ISSUE THREAD

**Issue by kevinfaveri** [credija/opa#58]
Hey there!

@Nyco @matzeso @albertosrocha

I currently have two Web Summit Open-Source Initiative tickets, which allow access to the three days + Night Summit event. However, I probably won't be able to attend. 

So, if anyone is interested, just contact me at my LinkedIn: https://www.linkedin.com/in/kevin-de-faveri-aguiar-786972142/

As for infos about the event: https://websummit.com/

**Comment by acegilz** [comment]
Hello @kevinfaguiar 

I would buy the 2 tickets from you, trying to connect via linkedin but your profile does not allow.
Do you still have them?

**Comment by kevinfaveri** [comment]
Hi @acegilz... unfortunately I already gave the tickets.

**Comment by klaudiosinani** [comment]
@kevinfaguiar I apologize for bothering and for taking the initiative to write here, but I have two tickets (general attendee + a lot of the extras that come with them) that unfortunately I will not be using since I will not be able to attend. If you are still interested @acegilz please feel free to let me know, I would be happy to sell them back to you for less than the early bird price of course. 😁
